app:
  name: "parse-video"
  mode: "dev"
  port: 9997
  start_time: "2024-12-14"
  machine_id: 1
log:
  level: "debug"
  log_dir: "/storage/log"
  filename: "server.log"
  max_size: 200
  max_age: 30
  max_backups: 7
db:
  type: "mysql"
  host: "127.0.0.1"
  port: 3306
  charset: "utf8mb4"
  prefix: ""
  user: "root"
  password: "root"
  dbname: "local_parse_video"
  set_max_open_conns: "20"
  set_max_idle_conns: "10"
  log_mode: "info"
  log_filename: "sql.log"
  enable_file_log_writer: true
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
jwt:
  secret: "3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s"
  expire_time: "7d"
